### ISSUE TITLE
Ca't connect to testnet

### ISSUE THREAD

**Issue by bacao1994** [freddiecoleman/chia-client#25]
I try to set up a CHIA local testnet blockchain. 
Could you give me some idea to set up this lib interact with testnet. 
Many thanks.
My issue below:

Error: ENOENT: no such file or directory, open '/home/caodb/.chia/mainnet/config/config.yaml'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.exports.getChiaConfig (/home/caodb/CaoDinh/projects/CHIA/chia-client-test/node_modules/chia-client/dist/src/ChiaNodeUtils.js:17:30)
    at Object.<anonymous> (/home/caodb/CaoDinh/projects/CHIA/chia-client-test/node_modules/chia-client/dist/src/FullNode.js:6:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)

**Comment by freddiecoleman** [comment]
Hmm. Looks like it defaults to mainnet directory. To work around that you could read the file into a buffer and pass that in the config options for cert/key/ca.
